services:
  nginx:
    build: ./nginx/
    ports:
      - 8080:8080

    volumes:
      - ./src/:/var/www/html/

  php:
    build: .
    expose:
      - 9000
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /var/www/html/
        - action: rebuild
          path: composer.json
          target: /var/www/html/
        - action: rebuild
          path: composer.lock
          target: /var/www/html/

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: jhajfvnakjeioafjo
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
