services:
  nginx:
    build: ./nginx/
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: ./nginx/default.conf
          target: /etc/nginx/conf.d/default.conf

  php:
    build: .
    expose:
      - 9000
    env_file: ".env"
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /var/www/html/
        - action: rebuild
          path: composer.json
          target: /var/www/html/
        - action: rebuild
          path: composer.lock
          target: /var/www/html/
        - action: rebuild
          path: .env
          target: /var/www/html/

  db:
    image: mysql:latest
    restart: always
    env_file: ".db.env"
    ports:
      - '3306:3306'
