services:
  nginx:
    build: ./nginx/
    ports:
      - 8080:8080

    volumes:
      - ./php/:/var/www/html/

  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./php/:/var/www/html/
    develop:
      watch:
        - action: sync
          path: ./php/src/
          target: /var/www/html/
        - action: rebuild
          path: ./php/composer.json
          target: /var/www/html/

#   db:
#     image: mariadb
#     volumes:
#       - mysql-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: mariadb
#       MYSQL_DATABASE: ecomdb

# volumes:
#   mysql-data:
