services:
  nginx:
    build: ./nginx/
    ports:
      - 8080:8080

  php:
    build: .
    expose:
      - 9000
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /var/www/html/
        - action: rebuild
          path: composer.json
          target: /var/www/html/
        - action: rebuild
          path: composer.lock
          target: /var/www/html/

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'kejaffkjekjsas'
      MYSQL_ROOT_PASSWORD: 'hafuheijkcnvjwah'
    ports:
      - '3306:3306'
